galaxy_info:
  author: Alex Sterlev
  description: Role for installing nginx

  license: MIT

  min_ansible_version: 2.0

  platforms:
    - name: CentOS
      versions:
        - 7

  galaxy_tags:
    - networking

dependencies: []
